[project]
name = "talkat"
version = "0.1.0"
description = "A voice command system with local model server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.1.1",
    "numpy>=2.2.6",
    "pyaudio>=0.2.14",
    "vosk>=0.3.45",
    "flask>=2.0",
    "requests>=2.20"
]

[project.scripts]
talkat = "talkat.cli:main"

[tool.uv]
dev-dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

